-- MySQL Script generated by MySQL Workbench
-- Mon Sep 18 19:52:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema inventario_poo_sas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inventario_poo_sas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventario_poo_sas` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `inventario_poo_sas` ;

-- -----------------------------------------------------
-- Table `inventario_poo_sas`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario_poo_sas`.`productos` (
  `idproductos` INT NOT NULL AUTO_INCREMENT,
  `nombre_pro` VARCHAR(45) NOT NULL,
  `precio` DECIMAL(18,2) NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`idproductos`))
ENGINE = InnoDB
AUTO_INCREMENT = 63
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `inventario_poo_sas`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario_poo_sas`.`vendedor` (
  `idvendedor` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(20) NOT NULL,
  `cedula` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idvendedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `inventario_poo_sas`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario_poo_sas`.`ventas` (
  `idventas` INT NOT NULL AUTO_INCREMENT,
  `idvendedo` INT NOT NULL,
  `nombreCliente` VARCHAR(45) NOT NULL,
  `numeroVenta` VARCHAR(244) NOT NULL,
  `fechaVenta` VARCHAR(45) NOT NULL,
  `monto` DECIMAL(4,2) NOT NULL,
  PRIMARY KEY (`idventas`),
  INDEX `fk_ventavendedor_idx` (`idvendedo` ASC) VISIBLE,
  CONSTRAINT `fk_ventavendedor`
    FOREIGN KEY (`idvendedo`)
    REFERENCES `inventario_poo_sas`.`vendedor` (`idvendedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 97
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `inventario_poo_sas`.`detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario_poo_sas`.`detalle` (
  `idDetalleVenta` INT NOT NULL AUTO_INCREMENT,
  `ventasIdVentas` INT NOT NULL,
  `producIdProduc` INT NOT NULL,
  `nombreProd` VARCHAR(50) NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DECIMAL(4,2) NOT NULL,
  `total` DECIMAL(4,2) NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDetalleVenta`),
  INDEX `ventasIdVentas_idx` (`ventasIdVentas` ASC) VISIBLE,
  INDEX `producIdProduc_idx` (`producIdProduc` ASC) VISIBLE,
  CONSTRAINT `producIdProduc`
    FOREIGN KEY (`producIdProduc`)
    REFERENCES `inventario_poo_sas`.`productos` (`idproductos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ventasIdVentas`
    FOREIGN KEY (`ventasIdVentas`)
    REFERENCES `inventario_poo_sas`.`ventas` (`idventas`))
ENGINE = InnoDB
AUTO_INCREMENT = 234
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `inventario_poo_sas`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario_poo_sas`.`proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `cedula_prov` VARCHAR(45) NOT NULL,
  `nombre_prov` VARCHAR(45) NOT NULL,
  `telefono_prov` VARCHAR(45) NOT NULL,
  `productos_prov` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
